export interface LiveStream {
  id: string;
  title: string;
  url: string;
  embedUrl: string;
  thumbnail: string | null;
  source: string;
  platform: "youtube" | "twitch" | "windy" | "other";
  isLive: boolean;
  region: string;
  lastChecked: string;
}

/**
 * Build YouTube embed URL from video ID
 */
function ytEmbed(videoId: string): string {
  return `https://www.youtube.com/embed/${videoId}?autoplay=1`;
}

/**
 * Webcam data sourced from signalcockpit.com/?tab=webcams
 * signalcockpit is a JS-rendered SPA so we maintain this list manually.
 * Last synced: 2026-03-04
 */
const SIGNALCOCKPIT_WEBCAMS: LiveStream[] = [
  // ─── YouTube Live Streams ───
  {
    id: "sc-iran-hd",
    title: "LIVE: Iran HD Camera Feeds from Tehran, Isfahan and More",
    url: "https://www.youtube.com/watch?v=-zGuR1qVKrU",
    embedUrl: ytEmbed("-zGuR1qVKrU"),
    thumbnail: "https://i3.ytimg.com/vi/-zGuR1qVKrU/sddefault.jpg",
    source: "SignalCockpit",
    platform: "youtube",
    isLive: true,
    region: "Iran",
    lastChecked: "",
  },
  {
    id: "sc-iran-multi",
    title: "Iran Multi Cam",
    url: "https://www.youtube.com/watch?v=4E-iFtUM2kk",
    embedUrl: ytEmbed("4E-iFtUM2kk"),
    thumbnail: "https://i3.ytimg.com/vi/4E-iFtUM2kk/sddefault.jpg",
    source: "SignalCockpit",
    platform: "youtube",
    isLive: true,
    region: "Iran",
    lastChecked: "",
  },
  {
    id: "sc-iran-israel-multi",
    title: "Iran and Israel Multi Cam",
    url: "https://www.youtube.com/watch?v=g6OG1_oPUj0",
    embedUrl: ytEmbed("g6OG1_oPUj0"),
    thumbnail: "https://i3.ytimg.com/vi/g6OG1_oPUj0/sddefault.jpg",
    source: "SignalCockpit",
    platform: "youtube",
    isLive: true,
    region: "Iran",
    lastChecked: "",
  },
  {
    id: "sc-iranian-news",
    title: "Iranian News Broadcast",
    url: "https://www.youtube.com/watch?v=A92pqZQAsm8",
    embedUrl: ytEmbed("A92pqZQAsm8"),
    thumbnail: "https://i3.ytimg.com/vi/A92pqZQAsm8/sddefault.jpg",
    source: "SignalCockpit",
    platform: "youtube",
    isLive: true,
    region: "Iran",
    lastChecked: "",
  },
  {
    id: "sc-aljazeera",
    title: "Al Jazeera English Live",
    url: "https://www.youtube.com/watch?v=gCNeDWCI0vo",
    embedUrl: ytEmbed("gCNeDWCI0vo"),
    thumbnail: "https://i3.ytimg.com/vi/gCNeDWCI0vo/sddefault.jpg",
    source: "SignalCockpit",
    platform: "youtube",
    isLive: true,
    region: "Orta Dogu",
    lastChecked: "",
  },
  // ─── Windy Webcams — Iran ───
  {
    id: "sc-windy-iran-goldare",
    title: "Goldare: Zala_trase",
    url: "https://windy.com/webcams/1678032287",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1678032287/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Iran",
    lastChecked: "",
  },
  // ─── Windy Webcams — Israel ───
  {
    id: "sc-windy-telaviv-tupim",
    title: "Tel Aviv-Yafo: Tupim Beach (Banana Drum Beach)",
    url: "https://windy.com/webcams/1639421838",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1639421838/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-herzliya-nw",
    title: "Herzliya: North-west",
    url: "https://windy.com/webcams/1642679224",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1642679224/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-telaviv-hilton",
    title: "Tel Aviv-Yafo: Hilton Beach",
    url: "https://windy.com/webcams/1748254982",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1748254982/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-herzliya-marina",
    title: "Herzliya: Marina Herzliya",
    url: "https://windy.com/webcams/1793900773",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1793900773/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-herzliya-2",
    title: "Herzliya",
    url: "https://windy.com/webcams/1793900776",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1793900776/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-jaffa-port",
    title: "Tel Aviv-Yafo: Old Jaffa - Jaffa Port",
    url: "https://windy.com/webcams/1793900793",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1793900793/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-telaviv-surf",
    title: "Tel Aviv-Yafo: Surf Academy Bayz - Hilton Beach",
    url: "https://windy.com/webcams/1793900794",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1793900794/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  // ─── Windy Webcams — Jerusalem ───
  {
    id: "sc-windy-jerusalem-1",
    title: "Jerusalem: Jesuralem",
    url: "https://windy.com/webcams/1389696018",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1389696018/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-jerusalem-old",
    title: "Jerusalem: Old City",
    url: "https://windy.com/webcams/1278244720",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1278244720/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-jerusalem-3",
    title: "Jerusalem",
    url: "https://windy.com/webcams/1663716177",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1663716177/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  {
    id: "sc-windy-jerusalem-4",
    title: "Jerusalem",
    url: "https://windy.com/webcams/1793900779",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1793900779/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Israel",
    lastChecked: "",
  },
  // ─── Windy Webcams — Saudi Arabia / Bahrain ───
  {
    id: "sc-windy-aludayd-1",
    title: "Al Udayd Governorate",
    url: "https://windy.com/webcams/1715973125",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1715973125/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Suudi Arabistan",
    lastChecked: "",
  },
  {
    id: "sc-windy-budaiya-1",
    title: "Budaiya",
    url: "https://windy.com/webcams/1716388379",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1716388379/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Bahrain",
    lastChecked: "",
  },
  {
    id: "sc-windy-budaiya-2",
    title: "Budaiya",
    url: "https://windy.com/webcams/1716388358",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1716388358/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Bahrain",
    lastChecked: "",
  },
  {
    id: "sc-windy-budaiya-3",
    title: "Budaiya",
    url: "https://windy.com/webcams/1716388337",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1716388337/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Bahrain",
    lastChecked: "",
  },
  {
    id: "sc-windy-salwa-1",
    title: "Al Udayd Governorate: Salwa-Qatar port - Salwa Road",
    url: "https://windy.com/webcams/1734641747",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1734641747/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Suudi Arabistan",
    lastChecked: "",
  },
  {
    id: "sc-windy-budaiya-4",
    title: "Budaiya",
    url: "https://windy.com/webcams/1716388316",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1716388316/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Bahrain",
    lastChecked: "",
  },
  {
    id: "sc-windy-salwa-2",
    title: "Al Udayd Governorate: Salwa-Qatar port - Salwa Road",
    url: "https://windy.com/webcams/1734641915",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1734641915/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Suudi Arabistan",
    lastChecked: "",
  },
  {
    id: "sc-windy-aludayd-2",
    title: "Al Udayd Governorate",
    url: "https://windy.com/webcams/1793884512",
    embedUrl: "",
    thumbnail: "https://imgproxy.windy.com/_/preview/plain/current/1793884512/original.jpg",
    source: "Windy",
    platform: "windy",
    isLive: true,
    region: "Suudi Arabistan",
    lastChecked: "",
  },
];

/**
 * Fetch live streams — returns webcam data from signalcockpit catalog
 */
export async function fetchLiveStreams(): Promise<LiveStream[]> {
  const now = new Date().toISOString();
  return SIGNALCOCKPIT_WEBCAMS.map((s) => ({
    ...s,
    lastChecked: now,
  }));
}
